name: Deploy Docs

on:
  workflow_dispatch:
    branches: [main]

jobs:
  deploy-docs:
    permissions:
      contents: write
      issues: write
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: ./docfx.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
